apiVersion: apps/v1
kind: Deployment
metadata:
  name: kid-migrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kid-migrator
  template:
    metadata:
      labels:
        app: kid-migrator
    spec:
      containers:
        - name: kid-migrator
          image: kid-migrator:latest
          env:
            - name: SOURCE_URL
              value: jdbc:postgresql://source-db:5432/source
            - name: SOURCE_USER
              value: source_user
            - name: SOURCE_PASSWORD
              value: source_pass
            - name: TARGET_URL
              value: jdbc:postgresql://target-db:5432/target
            - name: TARGET_USER
              value: target_user
            - name: TARGET_PASSWORD
              value: target_pass
          volumeMounts:
            - name: config
              mountPath: /app/application.properties
              subPath: application.properties
      volumes:
        - name: config
          configMap:
            name: kid-migrator-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kid-migrator-config
data:
  application.properties: |
    migration.source.url=${SOURCE_URL}
    migration.source.user=${SOURCE_USER}
    migration.source.password=${SOURCE_PASSWORD}
    migration.target.url=${TARGET_URL}
    migration.target.user=${TARGET_USER}
    migration.target.password=${TARGET_PASSWORD}
    migration.batchSize=1000
    migration.taskName=default-task
